apache/cloudstack-terraform-provider

- cloudstack/resource_cloudstack_instance.go
PR fixes: https://github.com/apache/cloudstack-terraform-provider/issues/4
The PR adds support to provide vm details - when using custom offering:
```
$ terraform apply 
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "cloudstack_instance" "web" {
+ display_name     = (known after apply)
+ expunge          = false
+ group            = (known after apply)
+ id               = (known after apply)
+ ip_address       = (known after apply)
+ name             = "server-1"
+ network_id       = "07b408a2-d65f-4654-be59-b964528153cd"
+ project          = (known after apply)
+ root_disk_size   = (known after apply)
+ service_offering = "custom" …
```
> Add support to provide VM details during VM deployment - when using custom offering

- cloudstack/resource_cloudstack_port_forward.go
This PR fixes the issue https://github.com/apache/cloudstack-terraform-provider/issues/21, where PF state is not updated properly in Terraform.
Verified steps:
1. Create VM and a new network
2. Acquire an IP
3. Create PF rule => successfully created
4. Make another attempt such that PF rule creation should fail
5. Retry with correct steps to get succeeded => successfully created
4 and 5 steps are the actual steps which got failed in the issue
> Fix port forwarding to update state only if there are no errors

- cloudstack/resource_cloudstack_ipaddress.go
When we try to destroy network/ip resource or complete setup destroy through terraform, the operation fails with following error
cloudstack_instance.web: Destruction complete after 11s
╷
│ Error: Error disassociating IP address b4b3aca3-57b6-4469-9a8a-19b896898845: Undefined error: {"errorcode":530,"errortext":"ip address is used for source nat purposes and can not be disassociated."}
│ 
Problem statement:
As part of the IP resource destroy, provider tries to dissociate, which is not required when the source nat is enabled.
Solution:
To skip disassociation if source nat is enabled on the IP. As part of this sourcenat property has to be added to the terraform state
> Fix ip address deletion during "terraform destory" command

- .gitignore
- cloudstack/provider.go
- cloudstack/resource_cloudstack_kubernetes_version.go
- cloudstack/resource_cloudstack_kubernetes_version_test.go
- go.mod
- go.sum
Adding support for Kubernetes ISOs
Contains the following actions :
- Create
- Update (enable / disable)
- Delete
```
TF_ACC=1 go test -run TestAccCloudStackKubernetesVersion* -v github.com/terraform-providers/terraform-provider-cloudstack/cloudstack
=== RUN   TestAccCloudStackKubernetesVersion_basic
--- PASS: TestAccCloudStackKubernetesVersion_basic (1.62s)
=== RUN   TestAccCloudStackKubernetesVersion_update
--- PASS: TestAccCloudStackKubernetesVersion_update (1.58s)
PASS
ok      github.com/terraform-providers/terraform-provider-cloudstack/cloudstack 3.209s
```
> Adding support for Kubernetes ISOs

- cloudstack/data_source_cloudstack_template.go
This PR fixes an issue with template datasource where provider crashes when using `display_text` as a filter, i.e. issue# https://github.com/apache/cloudstack-terraform-provider/issues/42
> fix for using display_text as a filter in template datasource

- cloudstack/resource_cloudstack_network.go
- website/docs/r/network.html.markdown
This PR adds the attribute `source_nat_ip_address` to the `cloudstack_network` resource, which can be passed to provisioner connection blocks (host parameter).
This PR fixes #16 and will save a lot of wasted IP addresses :)
> Add source_nat_ip_address attribute to cloudstack_network resource

- cloudstack/resource_cloudstack_instance.go
With this admin user can pass the hostid parmeter 
https://cloudstack.apache.org/api/apidocs-4.17/apis/deployVirtualMachine.html
> Added hostid parameter for deploying virtual machine

- cloudstack/resource_cloudstack_instance.go
- website/docs/r/instance.html.markdown
This PR fixes #61 , 
Added cluster_id parmeter to cloudstack_instance resource
https://github.com/apache/cloudstack-terraform-provider/issues/61
> added cluster_id parameter and modified hostid to host_id

- cloudstack/data_source_cloudstack_zone.go
The attribute `.id` for the `data.cloudstack_zone`  was returning `Name`  instead of `Id`
> Fix: zone data source not returning Id

- website/docs/r/account.html.markdown
- website/docs/r/disk_offering.html.markdown
- website/docs/r/domain.html.markdown
- website/docs/r/kubernetes_cluster.html.markdown
- website/docs/r/kubernetes_version.html.markdown
- website/docs/r/network_offering.html.markdown
- website/docs/r/service_offering.html.markdown
- website/docs/r/user.html.markdown
- website/docs/r/volume.html.markdown
- website/docs/r/zone.html.markdown
* Account
* Disk Offering
* Domain
* Kubernetes (version & Cluster)
* Network Offering
* Service Offering
* User
* Volume
* Zone
> Add docs for new resources

- README.md
- website/docs/README.md
This makes it a little easier to navigate the markdown files directly from the git repo and not rely on the external TF Registry doc site.
> Add TOC README.md for better nav. of docs in repo

- cloudstack/resource_cloudstack_instance.go
- website/docs/r/instance.html.markdown
This PR fixes #87 
Added Pod id to the cloudstack instance resource 
https://registry.terraform.io/providers/cloudstack/cloudstack/latest/docs/resources/instance
> added podid parameter

- cloudstack/resource_cloudstack_template.go
Fixes https://github.com/apache/cloudstack-terraform-provider/issues/48
> Support adding templates in all zones

- cloudstack/resource_cloudstack_kubernetes_cluster.go
- website/docs/r/kubernetes_cluster.html.markdown
This PR fixes #41 
https://cloudstack.apache.org/api/apidocs-4.19/apis/createKubernetesCluster.html
noderootdisksize` - (Optional) root disk size in GB for each node
> added noderootdisksize parameter

- .github/workflows/testacc.yml
- README.md
- cloudstack/resource_cloudstack_service_offering.go
- cloudstack/resource_cloudstack_service_offering_test.go
- website/docs/r/service_offering.html.markdown
Hi,
Here is some improvement in the `cloudstack_service_offering` resource so we can specify the `cpu_number`, `cpu_speed` and `memory` now.
I've added the acceptance test CI which can be run with different versions of Cloudstack. Although it is failing, the specific test for this change is passing:
```
=== RUN   TestAccCloudStackServiceOffering_basic
--- PASS: TestAccCloudStackServiceOffering_basic (0.33s)
```
Also, I made a change in the README to include the updated version of the `cloudstack-simulator`.
> Improves service offering resource

- cloudstack/resource_cloudstack_instance.go
- website/docs/r/instance.html.markdown
This adds a new boolean parameter to the cloudstack_instance resource, called "uefi". When set, the instance will boot in UEFI/Legacy mode.
> Add UEFI support

- cloudstack/resource_cloudstack_ipaddress.go
- cloudstack/resource_cloudstack_ipaddress_test.go
Fixes https://github.com/apache/cloudstack-terraform-provider/issues/32
> Fail when both network_id & vpc_id are set in ipaddress

- performrelease.sh
md5 deprecated
sha512 use specific tool for easy validation
> Update hash generation

- .github/workflows/acceptance.yml
Runs the Acceptance Tests when the `go.mod` and `go.sum` get changed. This will allow testing the dependency updates, specially by dependabot.
> ci: runs acc test on every change

- .github/workflows/acceptance.yml
Adds the terraform v1.9 and removes the v1.7 and adds the opentofu v1.7 and updates Cloudstack to v4.18.2.1 and v4.19.0.2.
> ci: update terraform, opentofu and cloudstack versions

- cloudstack/resource_cloudstack_instance.go
- cloudstack/resource_cloudstack_instance_test.go
Removes de fixed max size for user-data on the creation of the instance. As this value is configurable in the Cloudstack backend, provider will handover the conditional check to the Cloudstack management.
> fix: remove user-data conditional size

- .github/actions/setup-cloudstack/action.yml
- .github/workflows/acceptance.yml
Fixes #189
* Updated to use latest minor.patch Cloudstack (LTS) Versions
* Fix auth issue with using CMK instead curl
* Added some extra debug info (-S in curl will output errors, but keep output minimal otherwise)
* Created `action` folder and moved actions there
> Update github workflow & acceptance versions

- README.md
This PR is to add instruction for specific test execution
> add specific test instruction and 4.20.1 docker simulator

- cloudstack/resource_cloudstack_service_offering.go
- cloudstack/resource_cloudstack_service_offering_test.go
- website/docs/r/service_offering.html.markdown
Fixes #182 
Adds params for Custom offerings. Constrained custom offerings allow min/max values for CPU and memory. Also adds params for encrypt root and storage tags.
New params added,
- customized
- min_cpu_number
- max_cpu_number
- min_memory
- max_memory
- encrypt_root
- storage_tags
> serviceoffering: add params for custom offering, storage tags, encryptroot

- cloudstack/resource_cloudstack_instance.go
- website/docs/r/instance.html.markdown
Fixes https://github.com/apache/cloudstack-terraform-provider/issues/68
Changes in these fields is ignored as of now.
> Add disk_offering & override_disk_offering to instance resource

- cloudstack/resource_cloudstack_instance.go
> Fix update of VM details

- website/docs/r/private_gateway.html.markdown
The [example usage](https://registry.terraform.io/providers/cloudstack/cloudstack/latest/docs/resources/private_gateway#example-usage) of the `cloudstack_private_gateway` resource lacks the required `acl_id` parameter. This PR adds the required parameter to the example usage.
> Add `acl_id` parameter to the example usage of the `cloudstack_private_gateway` resource

- cloudstack/resource_cloudstack_kubernetes_cluster.go
Add registry credentials to cks creation, and caàtch failures on creation on for better state
> CKS registry and state updates

- cloudstack/resource_cloudstack_network_acl_rule.go
This commit addresses multiple issues in the `cloudstack_network_acl_rule` resource to improve reliability and compatibility with configurations lacking port specifications:
1. **Fix `aclid` usage in `createNetworkACLRule`**:
- Replaced `p.SetAclid(d.Id())` with `p.SetAclid(d.Get("acl_id").(string))` to use the configured `acl_id` instead of the unset resource ID during creation. This resolves CloudStack API error 431 (CSExceptionErrorCode: 9999) caused by an empty `aclid` value.
2. **Support TCP/UDP rules without ports**: - Modified `createNetworkACLRule` to create rules for TCP/UDP protocols when no ports are specified, using a default "all ports" rule with a UUID stored as `all_ports`. This ensures compatibility with configs omitting the optional `ports` attribute. - Updated …
> fix: Enhance network ACL rule creation & reading
